---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
 
```{r}
library(ggplot2)
library(plotly)
library(readr)
library(lubridate)
library(stringr)
library(ggthemes)
library(extrafont)
library(mosaic)
library(dplyr)
library(tidyvers)
```




```{r}
dataset <- X2020VAERSData
dataset<- dataset[ , c("VAERS_ID", "STATE", "AGE_YRS")]
dataset
```


```{r}
a <- X2020VAERSSYMPTOMS
a <- a[ , c("VAERS_ID", "SYMPTOM1")]
duplicated(a)
a <- a[!duplicated(a$VAERS_ID), ]
a

```


```{r}
dataset["SYMPTOM"] <- a["SYMPTOM1"]
dataset

```
```{r}
graph.CO = dataset %>%
  ggplot(aes(x=STATE, y=AGE_YRS, fill = SYMPTOM, +
  geom_tile() +
  theme_minimal() +
  scale_fill_gradient(low = "black", high = "#8de1f0"))) +
  labs(title = "COVID Symptoms") +
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        text = element_text(family="DM Sans"),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none")


```

```{r}
font = list(
  family = "DM Sans",
  size = 15,
  color = "white"
)
label = list(
  bgcolor = "#232F34",
  bordercolor = "transparent",
  font = font
)

CO = ggplotly(graph.CO, tooltip=c("x", "y", "text")) %>%
  style(hoverlabel = label) %>%
  layout(font = font,
         yaxis = list(fixedrange = TRUE),
         xaxis = list(fixedrange = TRUE)) %>%
  config(displayModeBar = FALSE)
```


```{r}
graph.COCO = CO %>%
  ggplot(aes(x=STATE, y=AGE_YRS, fill = SYMPTOM
                         )) +
  geom_point() +
  theme_minimal() +
  labs(title = "Covid Vaccine symptoms by Age and State ") +
  xlab("Symptom") +
  ylab("Year")
   
```


```{r}
ggplotly(graph.COCO)
```



